[package]
name = "stund-cli"
version = "0.1.0"
authors = ["Peter Williams <peter@newton.cx>"]

[workspace]

[dependencies]
atty = "0.2"
bincode = "1.0"
byteorder = "1.2"
daemonize = "0.2"
failure = "0.1"
futures = "0.1"
libc = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
state_machine_future = "0.1"
structopt = "0.2"
stund = { path = "stund", version = "0.1.0" }
tokio-core = "0.1"
tokio-executor = "0.1"
tokio-io = "0.1"
tokio-pty-process = { path = "tokio-pty-process", version = "0.1.0" }
tokio-serde-json = { git = "https://github.com/carllerche/tokio-serde-json" }
#tokio-signal2 = { path = "tokio-signal2", version = "0.1.0" }
tokio-signal = "0.1"
tokio-stdin = "0.1"
tokio-uds = "0.1"
unix_socket = "0.5"
