[package]
name = "tokio-pty-process"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>", "Peter Williams <peter@newton.cx>"]
license = "MIT/Apache-2.0"

[dependencies]
futures = "0.1"
libc = "0.2"
mio = "0.6"
tokio-core = "0.1"
tokio-io = "0.1"
tokio-signal = "0.1"
